### ISSUE TITLE
When starting up Bittrex websocket, intermittent InvalidOperationException

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#216]
Repro:
1. Create new ExchangeBittrexAPI
2. Subscribe to all symbols' order book socket

Result:
Intermittently, I get this error:

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Connection was disconnected before invocation result was received.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ExchangeSharp.SignalrManager.SignalrSocketConnection.<OpenAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ExchangeSharp.ExchangeBittrexAPI.BittrexWebSocketManager.SubscribeToExchangeDeltas(Action`1 callback, String[] symbols)
   at ExchangeSharp.ExchangeBittrexAPI.OnGetOrderBookDeltasWebSocket(Action`1 callback, Int32 maxCount, String[] symbols)
   at ExchangeSharp.ExchangeAPI.GetOrderBookDeltasWebSocket(Action`1 callback, Int32 maxCount, String[] symbols)
   at ExchangeSharp.ExchangeAPIExtensions.GetOrderBookWebSocket(IExchangeAPI api, Action`1 callback, Int32 maxCount, String[] symbols)

**Comment by jjxtra** [comment]
I am not able to duplicate in exchange sharp console with command line: websocket-ticker exchangeName=Bittrex

How often does it happen for you?

**Comment by jjxtra** [comment]
This should be resolved now. Let me know how it goes.
