### ISSUE TITLE
Bittrex sockets bug when subscribing too quickly - InvalidOperationException: Data cannot be sent because the connection is in the disconnected state. 

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#241]
I think this happens because the socket isn't fully connected before the subscribe message is sent. Not sure if the bug is in GetOrderBookWebSocket or in the Signalrmanager handling code. 

2018-08-13 23:02:29,576 [12] INFO  Worker.Exchange - Populating markets for Bittrex
2018-08-13 23:02:31.3940|ERROR|ExchangeSharp.Logger|Error invoking hub proxy SubscribeToExchangeDeltas: System.InvalidOperationException: Data cannot be sent because the connection is in the disconnected state. Call start before sending any data.
   at Microsoft.AspNet.SignalR.Client.Connection.Send(String data)
   at Microsoft.AspNet.SignalR.Client.Hubs.HubProxy.Invoke[TResult,TProgress](String method, Action`1 onProgress, Object[] args)
   at Microsoft.AspNet.SignalR.Client.Hubs.HubProxy.Invoke[T](String method, Object[] args)
   at ExchangeSharp.SignalrManager.SignalrSocketConnection.<OpenAsync>d__10.MoveNext() in D:\Git\CryptoArbs\ExchangeSharp\ExchangeSharp\Utility\SignalrManager.cs:line 92: System.InvalidOperationException: Data cannot be sent because the connection is in the disconnected state. Call start before sending any data.
   at Microsoft.AspNet.SignalR.Client.Connection.Send(String data)
   at Microsoft.AspNet.SignalR.Client.Hubs.HubProxy.Invoke[TResult,TProgress](String method, Action`1 onProgress, Object[] args)
   at Microsoft.AspNet.SignalR.Client.Hubs.HubProxy.Invoke[T](String method, Object[] args)
   at ExchangeSharp.SignalrManager.SignalrSocketConnection.<OpenAsync>d__10.MoveNext() in ExchangeSharp\ExchangeSharp\Utility\SignalrManager.cs:line 92

**Comment by jjxtra** [comment]
Should already be connected at that point. AddListener calls ReconnectLoop which ensures the connection. But I might be missing something clearly.

**Comment by bichuga** [comment]
Add more logging and we can see if things are happening out of order

**Comment by jjxtra** [comment]
Checked in some code. To reproduce, run 

```websocket-orderbook exchangeName=Bittrex symbols=*```

and press space bar after one second.

It takes a few seconds to send the several hundred market symbols to Bittrex to request order books for. During the loop, if the manager connection is closed / disposed, this exception will be thrown. The new code will restart the loop if it's simply a matter of a connection issue. If the connection or manager are disposed, the loop will end.
