### ISSUE TITLE
Net Core 2.0 InvalidCastException: Object must implement IConvertible

### ISSUE THREAD

**Issue by lgarcia11** [jjxtra/ExchangeSharp#25]
The following code for KrakenAPI throws error on Net Core 2.0

` ExchangeKrakenAPI api = new ExchangeKrakenAPI();`
  `ExchangeTicker ticker = api.GetTicker("USDTZUSD");`

System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at ExchangeSharp.CryptoUtility.ConvertInvariant[T](Object obj, T defaultValue)
   at ExchangeSharp.ExchangeKrakenAPI.GetTicker(String symbol)

**Comment by jjxtra** [comment]
Pushed fix to master

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by padmee** [comment]
thx! you are awesome!
