### ISSUE TITLE
[2 BUGS] [Bitfinex] OnGetCompletedOrderDetailsWebSocket

### ISSUE THREAD

**Issue by reathh** [jjxtra/ExchangeSharp#314]
Both bugs that I found are related to `OnGetCompletedOrderDetailsWebSocket()` for the Bitfinex API.

**Bug 1**
On line 507 there is this conditional
`if (token is JArray array && array.Count > 1 && array[2] is JArray && array[1].ToStringInvariant() == "os")`
Sometimes the value of token is: `{[ 0, "hb" ]}` and because we're checking `&& array[2]` while there isn't a [2] index, this error is thrown:
```
2018-12-05 11:36:12.0918 INFO System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ExchangeSharp.ExchangeBitfinexAPI.<>c__DisplayClass35_0.<OnGetCompletedOrderDetailsWebSocket>b__0(IWebSocket _socket, Byte[] msg) in ExchangeSharp\API\Exchanges\Bitfinex\ExchangeBitfinexAPI.cs:line 507
   at ExchangeSharp.ClientWebSocket.MessageTask() in ExchangeSharp\Utility\ClientWebSocket.cs:line 504
2018-12-05 11:36:22.0984 INFO System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
```

**Proposal for bug fix:**: If we edit ` && array.Count > 1` to ` && array.Count > 2` I think the problem will be solved.

**Bug 2**
When we actually receive a "os" callback and enter the conditional, this error is risen from the `ParseOrderWebSocket()`:
```
{System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Decimal.Parse(String s, NumberStyles style)
   at ExchangeSharp.CryptoUtility.ConvertInvariant[T](Object obj, T defaultValue) in C:\Users\ivelin\Documents\Projects\VisualStudio\SamoletBot\ExchangeSharp\Utility\CryptoUtility.cs:line 230
   at ExchangeSharp.ExchangeBitfinexAPI.ParseOrderWebSocket(JToken order) in ExchangeSharp\API\Exchanges\Bitfinex\ExchangeBitfinexAPI.cs:line 819
   at ExchangeSharp.ExchangeBitfinexAPI.<>c__DisplayClass35_0.<OnGetCompletedOrderDetailsWebSocket>b__0(IWebSocket _socket, Byte[] msg) in ExchangeSharp\API\Exchanges\Bitfinex\ExchangeBitfinexAPI.cs:line 511
   at ExchangeSharp.ClientWebSocket.MessageTask() in ExchangeSharp\Utility\ClientWebSocket.cs:line 504}
```

The problem is from the DateTime. `CryptoUtility.UnixTimeStampToDateTimeMilliseconds(order[8].ConvertInvariant<long>())` this line expects order[8] to be a number, while it's a `2018-12-05T09:39:06Z` normal datetime.
```
{[
  19890417194,
  "BTCUSD",
  0.002,
  0.002,
  "LIMIT",
  "ACTIVE",
  3000,
  0,
  "2018-12-05T09:39:06Z",
  0,
  0,
  0
]}
```

P.S. I don't know about you guys, but this method returns my OPEN orders. So this line at `ParseOrderWebSocket()` does not make sense: `Result = ExchangeAPIOrderResult.Filled`. This order isn't filled.

**Comment by vslee** [comment]
I'm sure if you sent a PR w/ these fixes, Jeff would be happy to merge them.
