### ISSUE TITLE
HitBTC AccountTransfer throws an ExchangeSharp.APIException   HResult=0x80131500   Message=<!DOCTYPE html>

### ISSUE THREAD

**Issue by jjziets** [jjxtra/ExchangeSharp#416]
I don't see the problem. There is enough balance in the account bank. keys are set up to allow. Any suggestion why this does not work?
Symbol is "NIM" 
Amount is dec 2000
ToBank = false 

        public async Task<bool> AccountTransfer(string Symbol, decimal Amount, bool ToBank)
        {
            var payload = await GetNoncePayloadAsync();
            payload["type"] = ToBank ? "exchangeToBank" : "bankToExchange";
            payload["currency"] = Symbol;
            payload["amount"] = Amount;
            JToken obj = await MakeJsonRequestAsync<JToken>("/account/transfer", null, payload);
            return (obj != null && obj.HasValues && !String.IsNullOrEmpty(obj["id"].ToStringInvariant()));
        }

ExchangeSharp.APIException
  HResult=0x80131500
  Message=<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/2/account/transfer</pre>
</body>
</html>

  Source=ExchangeSharp
  StackTrace:
   at ExchangeSharp.APIRequestMaker.<MakeRequestAsync>d__4.MoveNext() in ...ExchangeSharp\API\Common\APIRequestMaker.cs:line 216
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ExchangeSharp.BaseAPI.<MakeJsonRequestAsync>d__75`1.MoveNext() in ....API\Common\BaseAPI.cs:line 456
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ExchangeSharp.ExchangeHitbtcAPI.<AccountTransfer>d__33.MoveNext() in ...ExchangeSharp\API\Exchanges\Hitbtc\ExchangeHitbtcAPI.cs:line 472
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Binace_Auto_Sell.Form1.<button1_Click_1>d__3.MoveNext() in ....Hitbtc Auto Sell\Hitbtc Auto Sell\Form1.cs:line 143

**Comment by jjziets** [comment]
why is it showing "Cannot GET /api/2/account/transfer"
should it not be  POST?

https://api.hitbtc.com/#account-management
shows POST /api/2/account/transfer

**Comment by jjziets** [comment]
YES!!


this works

        public async Task<bool> AccountTransfer(string Symbol, decimal Amount, bool ToBank)
        {
            var payload = await GetNoncePayloadAsync();
            payload["type"] = ToBank ? "exchangeToBank" : "bankToExchange";
            payload["currency"] = Symbol;
            payload["amount"] = Amount;
            JToken obj = await MakeJsonRequestAsync<JToken>("/account/transfer", null, payload,"POST");
            return (obj != null && obj.HasValues && !String.IsNullOrEmpty(obj["id"].ToStringInvariant()));
        }
