### ISSUE TITLE
ExchangeBinanceAPI.GetCompletedOrdersForAllSymbolsAsync- System.Net.WebException: 'The remote server returned an error: (400) Bad Request.'

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#422]
System.Net.WebException
  HResult=0x80131509
  Message=The remote server returned an error: (400) Bad Request.
  Source=System
  StackTrace:
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ExchangeSharp.APIRequestMaker.<MakeRequestAsync>d__4.MoveNext() in C:\!Dev\ExchangeSharp-master(6)\ExchangeSharp\API\Common\APIRequestMaker.cs:line 182

![image](https://user-images.githubusercontent.com/38913162/63156612-59814100-c015-11e9-8aa6-848ad51481d8.png)

https://api.binance.com/api/v3/myTrades?timestamp=1565945591561&recvWindow=60000&symbol=LINKBTC&signature=04b1c8ba3c55c7e7ebd406b346515348357f7b59b5ea28228..............

**Comment by vslee** [comment]
Thanks for filing this bug. If you could send a pull request with the solution, we'll merge it. If you don't know how, you can also post the updated code here.

**Comment by gajewskiArek** [comment]
Not really sure what was original error since there's no responseString included in details but there's a problem with GetCompletedOrdersForAllSymbolsAsync method bacause it calls Parallel.ForEach with async lambdas. When you debug later you hit 
``
orders.Sort((o1, o2) =>
``
while orders still being empty. Same problem as discussed here:

https://stackoverflow.com/questions/15136542/parallel-foreach-with-asynchronous-lambda
