### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by happysammy** [jjxtra/ExchangeSharp#541]
When i get orderbook data through websocket, occasionally i encountered the error log: "The remote party closed the WebSocket connection without completing the close handshake", the complete stacktrace is as follows:

> 2020-05-20 11:08:45.3229 INFO System.Net.WebSockets.WebSocketException (540682606): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (540682606): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at ExchangeSharp.ClientWebSocket.ReadTask() in C:\Users\17868\Desktop\WorkSpace\ExchangeSharp-master\src\ExchangeSharp\Utility\ClientWebSocket.cs:line 429

I use dotnetcore 3.0 on ubuntu 18.04 system, and my test main function is as follows:
````
              public static async Task Main(string[] args)
		{			
			string[] symbolArray = new string[] { "eth_usdt", "eth_btc", "eos_usdt", "eos_btc", "qtum_usdt", "qtum_btc", "ht_btc", "ht_usdt", "btc_usdt", "bch_usdt" };
			foreach (var symbol in symbolArray)
			{
				var socketAPI = new ExchangeHuobiAPI();
				IWebSocket subResult = await socketAPI.GetDeltaOrderBookWebSocketAsync(ProcessOrderBook, 10, symbol);				
			}
			Console.ReadLine();			
		}

              private static void ProcessOrderBook(ExchangeOrderBook data)
		{
			Console.WriteLine($"receiveData={JsonConvert.SerializeObject(data)}");
		}
````

**Comment by vslee** [comment]
Thanks for filing this bug. If you'd like to investigate and send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.
